name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ 2985064405 }}
        password: ${{ 11qq22wwA2329E }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        tags: 2985064405/thintuit-app:latest

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.21.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
